version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridehive_manager_copy
    ports:
      - "8000:8000"
    depends_on:
      - db_copy
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db_copy
      - DB_PORT=3306
      - DB_DATABASE=ridehive_db_copy
      - DB_USERNAME=custom_user_copy
      - DB_PASSWORD=custom_password_copy
    volumes:
      - .:/var/www
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db_copy:
    image: mysql:8.0
    container_name: mysql_db_copy
    environment:
      MYSQL_DATABASE: ridehive_db_copy
      MYSQL_USER: custom_user_copy
      MYSQL_PASSWORD: custom_password_copy
      MYSQL_ROOT_PASSWORD: secure_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
